# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: opendata_genai_bot

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  #   - name: WhitespaceTokenizer
  #   - name: RegexFeaturizer
  #   - name: LexicalSyntacticFeaturizer
  #   - name: CountVectorsFeaturizer
  #   - name: CountVectorsFeaturizer
  #     analyzer: char_wb
  #     min_ngram: 1
  #     max_ngram: 4
  #   - name: DIETClassifier
  #     epochs: 100
  #     constrain_similarities: true
  #   - name: EntitySynonymMapper
  #   - name: ResponseSelector
  #     epochs: 100
  #     constrain_similarities: true
  #   - name: FallbackClassifier
  #     threshold: 0.3
  #     ambiguity_threshold: 0.1
  - name: SpacyNLP
    model: "es_core_news_sm"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  # # No configuration for policies was provided. The following default policies were used to train your model.
  # # If you'd like to customize them, uncomment and adjust the policies.
  # # See https://rasa.com/docs/rasa/policies for more information.
  #   - name: MemoizationPolicy
  #   - name: RulePolicy
  #   - name: UnexpecTEDIntentPolicy
  #     max_history: 5
  #     epochs: 100
  #   - name: TEDPolicy
  #     max_history: 5
  #     epochs: 100
  #     constrain_similarities: true
  - name: MemoizationPolicy
  - name: RulePolicy
  # - name: UnexpecTEDIntentPolicy
  #   max_history: 5
  #   epochs: 100
  - name: TEDPolicy
    max_history: 5 # cuidado con este parámetro, nos permite realizar conversaciones más complejas pero aumenta mucho el tiempo de entrenamiento
    epochs: 200
    batch_size: 50
    max_training_samples: 300
    constrain_similarities: true
