version: "3.7"

services:
  rasa:
    image: alexahumada/opendata-genai-bot-rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --endpoints
      - endpoints-pro.yml

    restart: unless-stopped
  action_server:
    image: alexahumada/opendata-genai-bot-actions:latest
    expose:
      - 5055
    restart: unless-stopped
  postgres:
    image: postgres:latest
    volumes:
      - rasa-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
      POSTGRES_DB: rasa
    restart: unless-stopped

volumes:
  rasa-postgres:
