version: "3.7"

services:
  rasa:
    image: alexahumada/opendata-genai-bot-rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:
    image: alexahumada/opendata-genai-bot-actions:latest
    expose:
      - 5055
  postgres:
    image: postgres:latest
    volumes:
      - rasa-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
      POSTGRES_DB: rasa

volumes:
  rasa-postgres:
