version: "3.7"

services:
  rasa:
    image: alexahumada/opendata-genai-bot-rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --debug
  action_server:
    image: alexahumada/opendata-genai-bot-actions:latest
    volumes:
      - ./actions:/app/actions
    expose:
     - 5055
    command:
      - start
      - --actions
      - actions.actions
      - --debug